### ISSUE TITLE
Incorrect temperature deplayed

### ISSUE THREAD

**Issue by stintov** [danielkaldheim/ha_airstage#14] opened 2023-10-16 07:18 UTC
Some of out units have started to display high values when off and not in use.

Integration version 1.1.3

![image](https://github.com/danielkaldheim/ha_airstage/assets/130797662/62d25f46-0213-43a3-bbc5-b601cc8f8a72)

**Comment by danielkaldheim** [comment] 2023-10-17 12:18
Thank you for filing this issue. Its a duplicate of https://github.com/danielkaldheim/ha_airstage/issues/4 so I will close this.

**Closed by danielkaldheim** 2023-10-17 12:18 UTC
