### ISSUE TITLE
AC Error Log

### ISSUE THREAD

**Issue by Janvier123** [danielkaldheim/ha_airstage#25] opened 2024-01-17 15:38 UTC
is it possible to pull error logs from the AC (in and/or out) ? They dont have to log directly to HA
I really dont want to install the APP just to check, it never remembers my login details, this integration works WAY better

Thx

**Comment by danielkaldheim** [comment] 2024-03-20 20:57
Duplicate of https://github.com/danielkaldheim/ha_airstage/issues/24

**Closed by danielkaldheim** 2024-03-20 20:57 UTC
