### ISSUE TITLE
Crazy high temperature value

### ISSUE THREAD

**Issue by stintov** [danielkaldheim/ha_airstage#13] opened 2023-10-10 21:32 UTC
Does anyone else have an isssue where the temperature is some crazy high value and it can't be changed. Attempting to set it back to 23 for example, it just goes back to 6000

![image](https://github.com/danielkaldheim/ha_airstage/assets/130797662/00d7690b-df0b-41bd-99a3-db82827077ba)

**Comment by danielkaldheim** [comment] 2023-10-11 08:27
Hi,
There was a bug when the unit was on "FAN ONLY" mode, this is fixed in version 1.1.2.

Please update, and if the issue still there let me know!

**Comment by danielkaldheim** [comment] 2023-10-11 08:35
Ok,

What mode are you using, fan only or other?

**Comment by stintov** [comment] 2023-10-11 08:38
Hi Daniel,

The unit isn't on at all. No settings are changed, I just added the integration yesterday.

What other information can I give you please. This is only on one unit, however I haven't touched anything on the other 5 units yet in HA.

![image](https://github.com/danielkaldheim/ha_airstage/assets/130797662/d514d413-c7ca-4607-817c-ade960dfbb35)

**Comment by danielkaldheim** [comment] 2023-10-11 08:53
Thank you for the screenshot. That helps!

The issue is related to error code 6553 which is what you see as temperature. Somehow this value is shown when the unit is off.

There's a somewhat similar issue regarding setting temperature / setting mode (https://github.com/danielkaldheim/ha_airstage/issues/12) which I'm currently investigation on.

I'll put a patch on the 6553 issue asap, and will do some more investegating.

If you set the unit on heat and change the temperature, does that work ok?

**Comment by IainMNorman** [comment] 2023-10-11 09:06
Wow. That's hot enough to boil, not melt, boil titanium :)

**Comment by danielkaldheim** [comment] 2023-10-11 10:05
Your correct @IainMNorman! 

@stintov I have updated the integration to version 1.1.3, and hopefully fixed the issue. Give it a try and let me know if it works!

**Comment by danielkaldheim** [comment] 2023-10-11 10:17
That should be correct. Your unit is reporting that the feature "Set temperature" is not available (error 65535).

Are you able to change temperature when you use heat mode or cool mode?

A screenshot of your device in Airstage App would also be very helpful if you could share?

**Comment by stintov** [comment] 2023-10-11 10:25
Here you go
![image](https://github.com/danielkaldheim/ha_airstage/assets/130797662/482b561f-4ba4-4e24-9f87-9e15e0fce713)

and from HA

![image](https://github.com/danielkaldheim/ha_airstage/assets/130797662/36d84dc3-fa63-4b93-bb9c-fb720e53750e)

Just a note, i'm not able to power on the AC unit from HA integration, I have to use Airstage.

Yes changing the temp via HA updates the airstage app too, so great job there.

**Comment by stintov** [comment] 2023-10-11 10:27
Interestingly it will turn off from HA just not on.

**Comment by danielkaldheim** [comment] 2023-10-11 10:33
Thanks!

That's interesting!
I'm able to turn off and on my unit. Is this only this one unit, or all of your units?

Maybe you can share your issue on https://community.home-assistant.io/t/fujitsu-air-conditioning-integration-airstage-dongle/ ? See if anyone have the same issue, could be a firmware issue?

**Comment by stintov** [comment] 2023-10-11 10:36
OK so if I press this button it starts, I presumes the on/off symbol was the one to use?
![image](https://github.com/danielkaldheim/ha_airstage/assets/130797662/85475e8d-d763-40a3-ac3e-f09af221d40f)

**Comment by danielkaldheim** [comment] 2023-10-11 10:41
Correct, you need to select mode to turn on the unit. The power button only turns off. I'm using the Home Assistant Default Climate entity which provide the modes / off button. 

Maybe I should add a power on / off switch on next release

**Comment by stintov** [comment] 2023-10-11 10:47
It makes sense once you know. On the physical remote you would press the power button to turn the unit on then select the heating cooling mode. Ultimatly user error from me.

**Comment by danielkaldheim** [comment] 2023-10-11 11:28
Allright! No worries!

I'm closing this issue, please feel free to open a new one if you find more bugs.

**Closed by danielkaldheim** 2023-10-11 11:28 UTC
Labels: bug, investigating
